name: Playwright Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.13"

      - name: Install Playwright dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-playwright

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Playwright Tests
        run: pytest tests  # Change to --headless if running in CI mode

      - name: Upload Playwright Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-report
          path: test-results.html  # Adjust if using a different report format